### ISSUE TITLE
make this dashboard

### ISSUE THREAD

**Issue by PaoGon** [PaoGon/embeded_finals_frontend#1]
the toogle button component is already in the repo
![image](https://user-images.githubusercontent.com/82503757/217672754-ac5649d0-15f2-49e5-9cd8-19336c78d4ee.png)

**Comment by gitmccoyabrasaldo** [comment]
![image](https://user-images.githubusercontent.com/105502328/217706235-bb4360e4-261e-494f-b77c-23bf4fd58ae7.png)

**Comment by gitmccoyabrasaldo** [comment]
![image](https://user-images.githubusercontent.com/105502328/217706393-281768e0-4a74-475f-87d3-77fb9871bc50.png)

**Comment by gitmccoyabrasaldo** [comment]
sakto na ba to
![image](https://user-images.githubusercontent.com/105502328/217723815-8a14b266-b9eb-4da5-b785-87b078cd59d3.png)

**Comment by gitmccoyabrasaldo** [comment]
pwede na ba to:

![image](https://user-images.githubusercontent.com/105502328/217725157-c14cd439-3afd-49dd-82a8-c8c99fe52f01.png)

**Comment by gitmccoyabrasaldo** [comment]
![image](https://user-images.githubusercontent.com/105502328/217725833-48e16600-4717-463e-bdbc-008756659719.png)

**Comment by gitmccoyabrasaldo** [comment]
eto na talaga hahaha 
![image](https://user-images.githubusercontent.com/105502328/217726572-08bf0b66-a26b-4aba-ba9c-e3498dd86e30.png)

**Comment by gitmccoyabrasaldo** [comment]
![image](https://user-images.githubusercontent.com/105502328/217727083-3535fff2-22b0-4d0e-98be-288efb611029.png)

**Comment by gitmccoyabrasaldo** [comment]
> the toogle button component is already in the repo ![image](https://user-images.githubusercontent.com/82503757/217672754-ac5649d0-15f2-49e5-9cd8-19336c78d4ee.png)

![image](https://user-images.githubusercontent.com/105502328/217755248-b33b7db1-8342-4250-a18d-e9afff30b492.png)
